# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StartMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StartMVVM

	  pod 'ReactiveKit', '~> 3.13'
	  pod 'Bond', '~> 7.6'


end
